export const catalogSeed = [
  {
    type: "product", slug: "atrin-necklace", sortOrder: 10,
    data: { image: "/images/Product-01.png", gallery: ["/images/Product-01.png", "/images/Collection-01.png", "/images/gallery-1.JPG"], category: "necklaces", collection: "signature", name: { fa: "گردنبند آترین", en: "Atrin Necklace" }, typeLabel: { fa: "گردنبند", en: "Necklace" }, positioning: { fa: "فرمی روشن برای همراهی روزمره و ماندگار.", en: "A luminous form for enduring everyday presence." }, story: { fa: "آترین از تعادل میان هندسه، نور و حرکت شکل گرفته است.", en: "Atrin is shaped by a balance of geometry, light, and movement." }, design: { fa: "اتصال‌های ظریف و تناسب کنترل‌شده، فرم مرکزی را برجسته می‌کنند.", en: "Refined links and controlled proportions frame the central form." }, specs: { weight: "7.2 g", karat: "18K", finish: { fa: "پرداخت براق", en: "Polished" } } },
  },
  {
    type: "product", slug: "vira-bracelet", sortOrder: 20,
    data: { image: "/images/Product-02.png", gallery: ["/images/Product-02.png", "/images/Collection-01.png", "/images/gallery-2.JPG"], category: "bracelets", collection: "signature", name: { fa: "دستبند ویرا", en: "Vira Bracelet" }, typeLabel: { fa: "دستبند", en: "Bracelet" }, positioning: { fa: "ریتمی معاصر با حضوری آرام.", en: "A contemporary rhythm with a quiet presence." }, story: { fa: "ویرا با تکرار سنجیده فرم‌ها، حرکت را به ساختار تبدیل می‌کند.", en: "Vira turns movement into structure through measured repetition." }, design: { fa: "پیوندهای هندسی برای انعطاف، دوام و همراهی روزانه طراحی شده‌اند.", en: "Geometric links are designed for flexibility, durability, and daily wear." }, specs: { weight: "11.5 g", karat: "18K", finish: { fa: "ترکیب مات و براق", en: "Satin and polish" } } },
  },
  {
    type: "product", slug: "mahtab-ring", sortOrder: 30,
    data: { image: "/images/Product-03.png", gallery: ["/images/Product-03.png", "/images/Collection-02.png", "/images/world-craft.webp"], category: "rings", collection: "heritage", name: { fa: "انگشتر مهتاب", en: "Mahtab Ring" }, typeLabel: { fa: "انگشتر", en: "Ring" }, positioning: { fa: "بازخوانی گل در هندسه‌ای زنده.", en: "A floral memory recast as living geometry." }, story: { fa: "مهتاب نقش گل را برای امروز ساده و بازتعریف می‌کند.", en: "Mahtab simplifies and redefines the floral motif for today." }, design: { fa: "تمرکز حجم در مرکز و حرکت تدریجی جزئیات، حضور و ظرافت را متعادل می‌کند.", en: "A concentrated center balances presence with refinement." }, specs: { weight: "4.9 g", karat: "18K", finish: { fa: "ترکیب مات و براق", en: "Satin and polish" } } },
  },
  {
    type: "product", slug: "nadia-earrings", sortOrder: 40,
    data: { image: "/images/Product-04.png", gallery: ["/images/Product-04.png", "/images/Collection-03.png", "/images/gallery-3.JPG"], category: "earrings", collection: "ceremony", name: { fa: "گوشواره نادیا", en: "Nadia Earrings" }, typeLabel: { fa: "گوشواره", en: "Earrings" }, positioning: { fa: "حرکت نور برای یک حضور رسمی.", en: "Light in motion for a ceremonial presence." }, story: { fa: "خطوط کشیده نادیا، نور را کنار چهره به ریتمی نرم تبدیل می‌کنند.", en: "Nadia's elongated lines turn light into a soft rhythm beside the face." }, design: { fa: "وزن بصری کنترل‌شده برای استایل‌های رسمی طراحی شده است.", en: "Controlled visual weight is designed for formal styling." }, specs: { weight: "5.6 g", karat: "18K", finish: { fa: "پرداخت براق", en: "Polished" } } },
  },
  {
    type: "product", slug: "leila-ring", sortOrder: 50,
    data: { image: "/images/Product-05.png", gallery: ["/images/Product-05.png", "/images/Collection-01.png", "/images/gallery-4.JPG"], category: "rings", collection: "signature", name: { fa: "انگشتر لیلا", en: "Leila Ring" }, typeLabel: { fa: "انگشتر", en: "Ring" }, positioning: { fa: "یک نقطه نور، در تعادلی روشن.", en: "A single point of light in clear balance." }, story: { fa: "لیلا از سکوت یک فرم خالص می‌آید.", en: "Leila comes from the quiet of a pure form." }, design: { fa: "رکاب ظریف، تمرکز را روی مرکز قطعه نگه می‌دارد.", en: "A refined band keeps attention on the center." }, specs: { weight: "4.2 g", karat: "18K", finish: { fa: "پرداخت آینه‌ای", en: "Mirror polish" } } },
  },
  {
    type: "product", slug: "raha-necklace", sortOrder: 60,
    data: { image: "/images/Product-06.png", gallery: ["/images/Product-06.png", "/images/Collection-03.png", "/images/gallery-main.JPG"], category: "necklaces", collection: "ceremony", name: { fa: "گردنبند رها", en: "Raha Necklace" }, typeLabel: { fa: "گردنبند", en: "Necklace" }, positioning: { fa: "فرمی روشن برای یک انتخاب شخصی.", en: "A luminous form for a personal choice." }, story: { fa: "رها درباره سبک شدن و حرکت آزاد نور است.", en: "Raha is about lightness and the free movement of light." }, design: { fa: "ابعاد متعادل و اتصال پنهان، تمرکز را روی فرم اصلی حفظ می‌کند.", en: "Balanced scale and a concealed bail keep focus on the central form." }, specs: { weight: "7.1 g", karat: "18K", finish: { fa: "پرداخت براق", en: "Polished" } } },
  },
  {
    type: "collection", slug: "signature", sortOrder: 10,
    data: { code: "SIGNATURE", hero: "/images/Collection-01.png", storyImage: "/images/Product-02.png", name: { fa: "امضای دیدار", en: "Didar Signature" }, positioning: { fa: "فرم‌هایی خالص برای حضوری آرام و ماندگار.", en: "Pure forms for a quiet, enduring presence." }, intro: { fa: "امضای دیدار، زبان طراحی خانه دیدار را در روشن‌ترین شکل خود بیان می‌کند.", en: "Didar Signature expresses the house design language in its clearest form." }, storyTitle: { fa: "وقتی سادگی، امضا می‌شود", en: "When simplicity becomes a signature" }, story: { fa: "هر خط در این کالکشن دلیل و تناسب خود را دارد.", en: "Every line in this collection has its own reason and proportion." }, themes: { fa: ["فرم معاصر", "جزئیات ظریف", "همراهی روزمره"], en: ["Modern form", "Fine detail", "Everyday presence"] }, products: ["atrin-necklace", "vira-bracelet", "leila-ring"] },
  },
  {
    type: "collection", slug: "heritage", sortOrder: 20,
    data: { code: "HERITAGE", hero: "/images/Collection-02.png", storyImage: "/images/collection-heritage.jpg", name: { fa: "میراث", en: "Heritage" }, positioning: { fa: "حافظه ایرانی، با بیانی برای امروز.", en: "Iranian memory, expressed for today." }, intro: { fa: "میراث گفت‌وگویی میان نقش‌های آشنا و زندگی معاصر است.", en: "Heritage creates a dialogue between familiar motifs and contemporary life." }, storyTitle: { fa: "ریشه‌ها، بدون تکرار گذشته", en: "Rooted without repeating the past" }, story: { fa: "هر موتیف به ساختار، ریتم و هندسه تبدیل می‌شود.", en: "Each motif becomes structure, rhythm, and geometry." }, themes: { fa: ["حافظه ایرانی", "هندسه ماندگار", "بیان معاصر"], en: ["Iranian memory", "Enduring geometry", "Modern expression"] }, products: ["mahtab-ring", "leila-ring", "vira-bracelet"] },
  },
  {
    type: "collection", slug: "ceremony", sortOrder: 30,
    data: { code: "CEREMONY", hero: "/images/Collection-03.png", storyImage: "/images/Product-04.png", name: { fa: "مراسم", en: "Ceremony" }, positioning: { fa: "برای لحظه‌هایی که در حافظه می‌مانند.", en: "For moments that remain in memory." }, intro: { fa: "مراسم برای لحظه‌ای طراحی شده که معنا، حضور و خاطره کنار هم قرار می‌گیرند.", en: "Ceremony is shaped for the moment meaning, presence, and memory meet." }, storyTitle: { fa: "درخشش، وقتی شخصی می‌شود", en: "When brilliance becomes personal" }, story: { fa: "هر قطعه بخشی از خاطره است، نه فقط بخشی از ظاهر.", en: "Each creation becomes part of the memory, not only the look." }, themes: { fa: ["لحظه‌های خاص", "درخشش آرام", "هدیه ماندگار"], en: ["Special moments", "Quiet brilliance", "Enduring gifts"] }, products: ["nadia-earrings", "raha-necklace", "atrin-necklace"] },
  },
];
